// unitrack-gen
//
// Fetch the project's remote config from the UniTrack portal, then emit a Swift
// file with one typed helper per CUSTOM convention kind declared in
// `snowplow.event_names` (after stripping the 5 built-in kinds the SDK ships).
//
//   swift run unitrack-gen \
//     --api-key   utk_xxx \
//     --config-url https://mobix.asia/event-tracking-mobile/config \
//     --output    ../../ios-camera-demo/UniTrackCameraDemo/UniTrackSnowplowGenerated.swift
//
// Re-run after the portal Convention table changes; commit the generated file.
// The generated helpers call SnowplowProvider.trackSelfDescribing(schema:data:…)
// with the pre-built iglu URI so there's zero runtime lookup.

import Foundation

// MARK: - CLI arg parsing

func argValue(_ flag: String) -> String? {
    let args = CommandLine.arguments
    guard let i = args.firstIndex(of: flag), i + 1 < args.count else { return nil }
    return args[i + 1]
}

guard let apiKey = argValue("--api-key") else {
    FileHandle.standardError.write(Data("error: --api-key required (your project's utk_… key)\n".utf8))
    exit(2)
}
guard let configURLString = argValue("--config-url") else {
    FileHandle.standardError.write(Data("error: --config-url required (e.g. https://mobix.asia/event-tracking-mobile/config)\n".utf8))
    exit(2)
}
guard let outputPath = argValue("--output") else {
    FileHandle.standardError.write(Data("error: --output required (path to Generated.swift)\n".utf8))
    exit(2)
}

guard let configURL = URL(string: configURLString) else {
    FileHandle.standardError.write(Data("error: --config-url is not a valid URL\n".utf8))
    exit(2)
}

// MARK: - Fetch portal config

print("[unitrack-gen] fetching \(configURLString) …")

var req = URLRequest(url: configURL)
req.setValue("Bearer " + apiKey, forHTTPHeaderField: "Authorization")
req.timeoutInterval = 10

let sem = DispatchSemaphore(value: 0)
var fetchData: Data?
var fetchErr:  Error?
URLSession.shared.dataTask(with: req) { d, _, e in
    fetchData = d; fetchErr = e; sem.signal()
}.resume()
sem.wait()

if let e = fetchErr {
    FileHandle.standardError.write(Data("error: fetch failed — \(e.localizedDescription)\n".utf8))
    exit(1)
}
guard let data = fetchData else {
    FileHandle.standardError.write(Data("error: empty response body\n".utf8))
    exit(1)
}

// MARK: - Parse the bits we care about

struct PortalConfig: Decodable {
    let snowplow: SnowplowBlock
    struct SnowplowBlock: Decodable {
        let iglu_vendor:     String?
        let default_version: String?
        let event_names:     [String: String]?
    }
}

let portal: PortalConfig
do {
    portal = try JSONDecoder().decode(PortalConfig.self, from: data)
} catch {
    FileHandle.standardError.write(Data("error: decode failed — \(error)\n".utf8))
    exit(1)
}

let vendor  = portal.snowplow.iglu_vendor     ?? "vn.fpt.ftel.snowplow"
let version = portal.snowplow.default_version ?? "1-0-0"
let allNames = portal.snowplow.event_names    ?? [:]

// SDK already ships typed helpers for these kinds — skip them so the generator
// doesn't emit a duplicate `trackingClick(…)` etc. that would conflict.
let builtin: Set<String> = ["click", "result", "screen_view", "crash", "api"]
let customKinds = allNames
    .filter { !builtin.contains($0.key) }
    .sorted { $0.key < $1.key }   // stable output → clean diffs

print("[unitrack-gen] vendor=\(vendor) version=\(version) custom_kinds=\(customKinds.count)")
for (k, v) in customKinds { print("  • \(k) → \(v)") }

// MARK: - Emit Swift

// Snake_case kind → CamelCase suffix appended to "tracking".
// "ev_error"  → "EvError"  → method name "trackingEvError"
// "ev_open"   → "EvOpen"   → "trackingEvOpen"
func camelSuffix(_ kind: String) -> String {
    kind.split(separator: "_")
        .map { $0.prefix(1).uppercased() + $0.dropFirst() }
        .joined()
}

let now = ISO8601DateFormatter().string(from: Date())
var lines: [String] = []
lines.append("""
// AUTO-GENERATED by `swift run unitrack-gen` — DO NOT EDIT BY HAND.
// Sourced from \(configURLString) on \(now).
// To refresh: re-run the generator after editing the Convention table on the portal.

import Foundation
import UniTrackSnowplow

#if canImport(SnowplowTracker)
import SnowplowTracker

public extension SnowplowProvider {
""")

if customKinds.isEmpty {
    lines.append("""
        // No custom convention kinds declared on the portal. Add some via the
        // Config tab → Snowplow → "+ Add convention kind", then re-run the generator.
    """)
} else {
    for (kind, resolved) in customKinds {
        let eventName = resolved.isEmpty ? kind : resolved
        let schema    = "iglu:\(vendor)/\(eventName)/jsonschema/\(version)"
        let fn        = "tracking" + camelSuffix(kind)
        lines.append("""

        /// Convention kind `\(kind)` → schema `\(schema)`.
        /// Generated from portal config; re-run unitrack-gen after the portal changes.
        func \(fn)(data: [String: Any]? = nil,
            \(String(repeating: " ", count: fn.count))extraContexts: [SelfDescribingJson]? = nil,
            \(String(repeating: " ", count: fn.count))skipGlobalContexts: Bool = false) {
            trackSelfDescribing(schema: "\(schema)",
                                data: data ?? [:],
                                extraContexts: extraContexts,
                                skipGlobalContexts: skipGlobalContexts)
        }
""")
    }
}

lines.append("""

}
#endif
""")

let output = lines.joined(separator: "\n") + "\n"

// MARK: - Write file

let outURL = URL(fileURLWithPath: outputPath)
do {
    try output.write(to: outURL, atomically: true, encoding: .utf8)
    print("[unitrack-gen] wrote \(outURL.path) (\(customKinds.count) helper(s))")
} catch {
    FileHandle.standardError.write(Data("error: write failed — \(error)\n".utf8))
    exit(1)
}
